apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-replication
    redis_setup_type: replication
    role: replication
    redis-role: master
  name: redis-replication-master
  namespace: default
spec:
  ports:
  - name: redis-client
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-replication
    redis_setup_type: replication
    role: replication
    redis-role: master
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-replication
    redis_setup_type: replication
    role: replication
    redis-role: replica
  name: redis-replication-replica
  namespace: default
spec:
  ports:
  - name: redis-client
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-replication
    redis_setup_type: replication
    role: replication
    redis-role: replica
  type: NodePort