# Operatorが自動生成したサービス(参考用)
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-04-05T10:02:28Z"
  labels:
    app.kubernetes.io/component: sentinel
    app.kubernetes.io/managed-by: redis-operator
    app.kubernetes.io/name: redisfailover-v7-0-10
    app.kubernetes.io/part-of: redis-failover
    redisfailovers.databases.spotahome.com/name: redisfailover-v7-0-10
  name: rfs-redisfailover-v7-0-10
  namespace: "71000000002"
  ownerReferences:
  - apiVersion: databases.spotahome.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: RedisFailover
    name: redisfailover-v7-0-10
    uid: 04f86385-8a74-4c73-b6b0-07acf29c4434
  resourceVersion: "4073118"
  uid: 2412202d-09e1-47a3-ae52-9d35b2d2be11
spec:
  clusterIP: 10.147.117.172
  clusterIPs:
  - 10.147.117.172
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: sentinel
    port: 26379
    protocol: TCP
    targetPort: 26379
  selector:
    app.kubernetes.io/component: sentinel
    app.kubernetes.io/name: redisfailover-v7-0-10
    app.kubernetes.io/part-of: redis-failover
  sessionAffinity: None
  type: ClusterIP